### ISSUE TITLE
Open editor when --title or --comment is passed without value

### ISSUE THREAD

**Issue by eduardolundgren** [node-gh/gh#34]

**Comment by johannestroeger** [comment]
hey!

i think also this would be a big improvement and i would like to tackle this issue. could somebody give me a hint where i could start?

i was thinking of using a combining of `child_process.spawn(process.env.EDITOR...` and `child_process.exec('mktemp'...`

**Comment by henvic** [comment]
@johannestroeger,

I would rely on `git config --global core.editor` because of Windows (and $EDITOR may be undefined, anyways).

There are a couple packages on npm to handle temporary files creation with node. You can search for 'tmp' or 'temporary file' and will find a lot.

Maybe you should find one that works fine (so you don't have to implement it / worry about cross-platform).

It should be something like this:

1. create temporary file with a template
2. open temporary file as text with the default editor
3. when the user closes the editor / file changes, continue

You probably want to use a format similar to git's commit messages: use # as a comment for the message; 1st line is the title; following lines are the description.

**Comment by slavaGanzin** [comment]
Why this wasn't done? I can do this. Or something block this?

**Comment by henvic** [comment]
@slavaGanzin, no special reason besides a large backlog.

If you can do it, please do it and send us a pull request.

**Comment by protoEvangelion** [comment]
@slavaGanzin @johannestroeger I know it has been a while, but since I am starting to work through the backlog, were you able to make any progress on this?

**Comment by slavaGanzin** [comment]
I have no time for now

**Comment by johannestroeger** [comment]
me neither
