### ISSUE TITLE
`Number.parseInt` is ES6, and might cause an error for users with older versions of node.

### ISSUE THREAD

**Issue by johnloy** [node-gh/gh#386]
Why not just use the global `parseInt()`?

https://github.com/node-gh/gh/commit/411d1157147a1a729566379b253d227d9c355f8f#diff-0d74af7a9210fce24286f2613ee81e97R157

**Comment by henvic** [comment]
Hey @johnloy, I've changed it to use the global `parseInt` and will release the changes within a few hours.

But I'm just wondering:
1 were you just browsing the code or have you had a problem due to it?
2. what node.js version are you using? gh only supports node >= 0.12 and there. `node -v`
3. what gh version are you using? `gh -v`

Thanks.

**Comment by johnloy** [comment]
@henvic Thanks for the change! I actually experienced an error while using gh, and was originally using node v0.10.x. I upgraded and had no problem afterwards. I'm using gh v1.11.7.

**Comment by henvic** [comment]
Okay. Are you using node v0.12.x now?
