### ISSUE TITLE
the default list view is now too verbose

### ISSUE THREAD

**Issue by rotty3000** [node-gh/gh#390]
After updating recently to the latest version, I discovered that the list view (`gh pr -a`) is now REALLY long! because it's showing the full description of the commit instead of just the text of the last commit as it used to.

Can we get a `-s` mode (single line list)? Or at least a way to revert to the old way?

As someone who reviews lots of commits the new listing is really hard to like since it means I have scroll a lot.

**Comment by henvic** [comment]
Hey @rotty3000,
I have reverted it.

This was a change introduced by mistake.

@mdelapenya actually made me aware of it somewhere (but he saw it as a feature, rather than as a bug) and I decided to ignore for a few days to see users' reactions. If nobody complained I'd keep it.

But now I see this can be a headache, so for consistency I am removing it instead of creating a -single-line flag and who enjoys it may from now on use -d or --detailed to achieve the same results.

https://github.com/node-gh/gh/commit/763b071b5540ae2432b0193d33977c2428867f45#diff-7b5723a7633cee3082faf1c643e8fdf9L7

I am releasing a new version in the few minutes. Hang tight.
