### ISSUE TITLE
gh pr <number> fails instead of updating/pulling

### ISSUE THREAD

**Issue by maxandersen** [node-gh/gh#400]
when one have run `gh pr 435` to get PR 435 it is not possible to actually get updates.

git pull results in error and running `gh pr 435` fails too, seeing:

```
~/c/j/jbosstools-website git:master ❯❯❯ gh pr 435                                                                   ✭
Fetching pull request #435 into branch pr-435
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 15 (delta 5), reused 0 (delta 0), pack-reused 0
Unpacking objects: 100% (15/15), done.
From github.com:gorkem/jbosstools-website
 ! [rejected]        NN-4.3.0.Beta2 -> pr-435  (non-fast-forward)
/usr/local/lib/node_modules/gh/lib/exec.js:49
        throw err;
              ^
Error: Child process terminated with error code 1
    at Object.exports.spawnSyncStream (/usr/local/lib/node_modules/gh/lib/exec.js:45:15)
    at Object.exports.fetch (/usr/local/lib/node_modules/gh/lib/git.js:70:17)
    at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:334:13
    at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/pullRequests.js:118:17
    at callCallback (/usr/local/lib/node_modules/gh/node_modules/github/index.js:743:17)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/gh/node_modules/github/index.js:796:25)
    at IncomingMessage.emit (events.js:129:20)
    at _stream_readable.js:908:16
    at process._tickCallback (node.js:355:11)
```

**Comment by henvic** [comment]
> It's not a bug, it's a feature.

This exception happens when a child process that is being executed exists with a non-zero error code.

Today I have started working a plan to improve it.

Basically I want to listen to the stdout / stderr and when there is a, say, merge rejection (in this case the word [rejected]) I want to just exit without showing the exception.

I have found a couple issues with child_process.spawnSync that made it way harder to do 'the right way' when piping the stdout / stderr to the parent process' stdout / stderr and couldn't figure out a way to do it properly without implementing a lot of code.

Tomorrow I am going to try to do a temporary workaround (listen to stdout / stderr) that worked nice in some tests I have made and is way clearer. If that works, I will use it.

**Comment by maxandersen** [comment]
any update on this ?

**Comment by henvic** [comment]
Sorry, but not yet. I have been very busy for a while and didn't have time to do this improvement yet :(

**Comment by henvic** [comment]
I have tried a few approaches, but they didn't work out nice and added a lot of code.

**Comment by protoEvangelion** [comment]
Closing to continue discussion here: #281
