### ISSUE TITLE
gh pr -a doesn't work well

### ISSUE THREAD

**Issue by zsoltbalogh** [node-gh/gh#413]
When running gh pr -a, it lists some random PR-s from the organization I belong to and not mine. I receive nothing back when I run gh pr --list --me --all.

**Comment by henvic** [comment]
Hey @zsoltbalogh,
do you belong to any other organization besides Liferay?

When you use `gh pr --list --me --all` it should list to all pull requests of repositories belonged to you.

Maybe the issue you're experiencing is that you're seeing only a few of them, and not pull requests you recognize. This might be because of the pagination limit. gh had it set to retrieve only a first page with 30 results, or: 30 repos at most. Many people, including myself, belong to about 100 repos so I have lifted the per_page option to 500, that should be more than enough for any sane person.

I have also made the same changes on the repo listing methods.

**Comment by henvic** [comment]
I have reopened the ticket and released v1.11.13 with the changes.

Please reinstall and if this is fixed, close the ticket. Otherwise, let me know so I can investigate more.

**Comment by henvic** [comment]
Oh, I see there's still a problem. These last changes actually only solve part of this. Hold on.

**Comment by zsoltbalogh** [comment]
Hi @henvic,

Thank you for the quick answers! When I try gh pr --list --me --all I get no PRs listed. The pagination limit seems to be interesting, however it should not be more than 30. Please let me know if I can help the investigation with any data.

Zsolt

**Comment by zsoltbalogh** [comment]
(I run my previous tests on gh 1.11.12)

**Comment by protoEvangelion** [comment]
This appears to be fixed. Please let me know if it is still an issue 😄
