### ISSUE TITLE
help

### ISSUE THREAD

**Issue by wbyoung** [node-gh/gh#420]

**Comment by henvic** [comment]
Yeah?

**Comment by wbyoung** [comment]
Must have accidentally been opened while working on a script. :wink:

**Comment by henvic** [comment]
No worries :smile: 

Someone, somewhere at my work should hate me for all the useless Jira tickets I have ever opened while working on [gh-jira](https://github.com/node-gh/gh-jira).

\* And just past month, when I have made a major refactoring of gh-jira, I have started using the staging area instead of the production environment (and I had to go back to the production environment sometimes when the staging was unstable due to other people messing around, I guess; this is what stages are made for, right?).
