### ISSUE TITLE
Cannot read property 'ssh_url' of null

### ISSUE THREAD

**Issue by robdodson** [node-gh/gh#436]
Just noticed this error this morning when I tried to use the `gh pr 123` command.
[Line 332 of pull-request.js seems to be breaking](https://github.com/node-gh/gh/blob/master/lib/cmds/pull-request.js#L332).

Running `git version 2.8.0.rc2`.

**Comment by henvic** [comment]
Hey @robdodson,

long time no see!

Please verify if the remote branch you are trying to pull still exists.

@brunofarache had a similar issue a 3-4 days ago due to the branch being removed from GitHub. I haven't submitted a fix for this yet (that would be adding a useful error message).

If the remote branch exists, please tell me if your remote is using SSH or HTTPS.

Best regards,
Henrique.

**Comment by robdodson** [comment]
Yep the remote exists (it's the master branch). It's using HTTPS

**Comment by protoEvangelion** [comment]
Someone on my team was getting an error as well when running `gh pr number`

```
Permission denied (publickey).
fatal: Could not read from remote repository.
```

The problem in this case was that they did not have ssh set up.

I added an option to disable ssh and use https instead via the `~/.gh.json` config:

```
"ssh": false
```
