### ISSUE TITLE
Can't use backticks in comment strings

### ISSUE THREAD

**Issue by meetmangukiya** [node-gh/gh#464]
I tried following command:
```
gh is -n 1 -c "Instead of parsing whole hmtl by regex, we must use modules like `lxml`"
```

I expected it to comment the `lxml` in a monospaced font. The comment can be found here
https://github.com/meetmangukiya/frisbee/issues/1#issuecomment-269066776

**Comment by sholladay** [comment]
This is user error, sorry to say. And it has to do with the shell rather than `gh`. You are using double quotes for the argument. The shell evaluates this, unlike single quotes. And backticks, as far as the shell is concerned, means to execute a command in a subshell.

To see what I mean, try running:

```bash
echo "foo `ls`"
```

I'll give you a hint: it's probably going to print more than a few characters.

I'm actually surprised you didn't see:

```console
-bash: lxml: command not found
```

Maybe you just missed it?

**Comment by henvic** [comment]
Nice catch, @sholladay.
