### ISSUE TITLE
vulnerabilities detected when running  npm audit

### ISSUE THREAD

**Issue by gghhh456** [node-gh/gh#557]
Hey there,

I get 3 vulnerabilities (2 low, 1 critical) after installing this package.

`npm --version  #6.4.0`

`node  -v #8.11.3`

![vulnerebility](https://user-images.githubusercontent.com/14292516/44576694-821e8400-a78f-11e8-8aae-085a137dc6e5.png)

**Comment by protoEvangelion** [comment]
@gghhh456 Thanks for reporting :)

Although the warnings were benign AFAIK, I went ahead and updated dependencies to get rid of the `npm audit` warnings.

A lot of these warnings are not an issue because they either exploit a running server like a DDoS attack  or rely on malicious user input. These types of exploits should not affect gh users.

It does feel nice though when the report comes back:

![image](https://user-images.githubusercontent.com/20076677/44625999-d88fdd80-a8c9-11e8-87c2-4740018fa20f.png)

Thanks again for reporting and let me know if you still see these warnings after running `npm install -g gh`
