### ISSUE TITLE
deprecation warming for `github` module

### ISSUE THREAD

**Issue by rotty3000** [node-gh/gh#642]
```
~]$ sudo npm i -g gh
npm WARN deprecated github@0.2.4: 'github' has been renamed to '@octokit/rest' (https://git.io/vNB11)
/usr/bin/gh -> /usr/lib/node_modules/gh/bin/gh.js
+ gh@1.17.3
updated 1 package in 5.231s
```

**Comment by protoEvangelion** [comment]
Hey @rotty3000 thanks for the nudge. We are in the process of upgrading to octokit/rest however the upgrade was a bit more involved than anticipated because they use promises.

GH was written in the era of callbacks so it will require literally rewriting everything to promised based :)

Keep an eye on it here: https://github.com/node-gh/gh/issues/612
