### ISSUE TITLE
Update all contributors badge in readme to be 82

### ISSUE THREAD

**Issue by protoEvangelion** [node-gh/gh#676]
There is a badge in the top of the readme.md file that shows how many contributors have contributed to node-gh. We need to update that to 81 because we are missing 1 person + yourself because you are contributing :tada:

**Comment by myluco** [comment]
Who is the person?

**Comment by protoEvangelion** [comment]
The last person I tried to add with the all contributors bot, it didn't update the Readme badge automatically. I opened an issue on their repo:  https://github.com/all-contributors/all-contributors-bot/issues/247

**Comment by protoEvangelion** [comment]
The person was added to the Readme but the badge wasn't updated.

**Comment by ahonn** [comment]
This problem seems to be because this line ends with `(#contributors-)`

![image](https://user-images.githubusercontent.com/9718515/65830712-a2026e80-e2e4-11e9-940c-b0e829a8f3bb.png)

[all-contributors-bot is using all-contributors-cli v6.7.0](https://github.com/all-contributors/all-contributors-bot/blob/master/package.json#L27). In all-contributors-cli v6.7.0, we can find these codes:

```
const badgeRegex = /\[!\[All Contributors\]\([a-zA-Z0-9\-./_:?=]+\)\]\(#\w+\)/
```

But this regular expression has been modified in [this commit](https://github.com/all-contributors/all-contributors-cli/commit/fdea80649d7bcb9df971cef5df00d8505e378049) of v6.9.1

Badge can't be updated correctly because of this, using both cli and bot will cause this problem.
Upgrading the cli version of all-contributors-bot dependencies should solve this problem.

**Comment by protoEvangelion** [comment]
Thanks for the thorough and quick report @ahonn!

I'll keep an eye on your open PR.

@myluco in the time being however, if you send a PR to update that number, I will be happy to merge it.

**Comment by protoEvangelion** [comment]
82 now

**Comment by protoEvangelion** [comment]
Closing because this will be handled automatically by https://github.com/all-contributors/all-contributors-bot/pull/250
