### ISSUE TITLE
Warnings when updating

### ISSUE THREAD

**Issue by jpince** [node-gh/gh#704]
**Version number**
2.3.0 (might have been introduced in an earlier version, I haven't updated in a while)

**Describe the bug**
Warning messages when updating 1.17.5 → 2.3.0
```
npm WARN enoent ENOENT: no such file or directory, open '/media/jpince/l/72x/package.json'
npm WARN marked-terminal@3.2.0 requires a peer of marked@^0.4.0 || ^0.5.0 || ^0.6.0 but none was installed.
npm WARN 72x No description
npm WARN 72x No repository field.
npm WARN 72x No README data
npm WARN 72x No license field.
```

**To Reproduce**

1. Start on version 1.17.5
1. Run Cmd 'sudo npm i gh'
1. See warnings at the end

**Expected behavior**
No warnings

**Comment by protoEvangelion** [comment]
Thanks for reporting @jpince I will take a look 👍

**Comment by jpince** [comment]
Thanks for keeping this up, Ryan. It's a great tool!

**Comment by protoEvangelion** [comment]
Those npm warnings are common :)

Node CLIs are usually designed to be installed in your npm global dir so they can be used anywhere. In GH's case, I'm actually surprised it still works for you because when we try to resolve modules we do a lookup on npm's global dir.

Closing now, but if anyone encounters this issue please reopen.

**Comment by jpince** [comment]
got it, thanks!
